apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mongo-deployment.yaml
  - mongodb-service.yaml
  - pacman-deployment.yaml
  - pacman-sa-scc-role-rb.yaml
  - pacman-svc.yaml
  - pvc.yaml
  - route.yaml
  - secret.yaml
