apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apiserversource-sa-role.yaml
  - apiserversource-sa-rolebinding.yaml
  - apiserversource-sa.yaml
  - apiserversource.yaml
  - brokers.yaml
  - eventtransform.yaml
  - ksvc-eventdisplay-trigger.yaml
  - ksvc-sockeye-trigger.yaml
  - trigger-vm-add-delete-event.yaml