apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubedescheduler.yaml
  - machineconfig-psi-karg-worker.yaml
  - machineconfig-psi-karg-master.yaml
  - operator.yaml
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml